# doc site configuration (mkdocs)
site_name: Hello There - documentation 
site_description: Documentation for the students of Zone01 Promotion 2024
theme:
  name: material
  logo: material/library
not_in_nav: |
  /private.md
# ignore
exclude_docs: |
  api-config.json    # A file with this name anywhere.
  /requirements.txt  # Top-level "docs/requirements.txt".
  *.py               # Any file with this extension anywhere.
  !.assets  # Don't exclude '.assets' although all other '.*' are excluded
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
plugins:
  - search
  - toggle-sidebar
  - mermaid2
  # - mermaid2:
  #   version: '9.4.3' # only works with version < 10
  #   arguments:
  #     theme: 'dark'
  #     themeVariables:
  #       primaryColor: '#BB2528'
  #       primaryTextColor: '#fff'
  #       primaryBorderColor: '#7C0000'
  #       lineColor: '#F8B229'
  #       secondaryColor: '#006100'
  #       tertiaryColor: '#fff'
  # - navigation.tabs
